
import time

def historia():
   
    print("╔══════════════════════════════════════════════════════════╗")
    time.sleep(0.5)
    print("║              ᖙ Em Busca da Aurora ᖚ                      ║")
    time.sleep(0.5)
    print("║                                                          ║")
    time.sleep(0.5)
    print("║     Em uma região pacata e calma no norte, Vincent,      ║")
    time.sleep(0.5)
    print("║     um camponês vive feliz com sua esposa e sua filha    ║")
    time.sleep(0.5)
    print("║     Aurora na sua vila junto com outras famílias, até    ║")
    time.sleep(0.5)   
    print("║     que um certo dia Aurora foi sequestrada pelo         ║")
    time.sleep(0.5)
    print("║     Feiticeiro Negro e aprisionada em um castelo ao      ║")
    time.sleep(0.5)
    print("║     longe da sua vila.                                   ║")
    time.sleep(0.5)
    print("║     Desolado pelo sequestro da sua filha, Vincent sai    ║")
    time.sleep(0.5)
    print("║     pela estrada em busca do caminho para o castelo      ║")
    time.sleep(0.5)
    print("║     do feiticeiro, neste caminho ele terá que solucionar ║")
    time.sleep(0.5)
    print("║     quebra-cabeças pela sua jornada e coletar itens      ║")
    time.sleep(0.5)
    print("║     para conseguir derrotar seu inimigo.                 ║")
    time.sleep(0.5)
    print("║     ⩥ Cabe a você ajuda-lo em sua jornada para           ║")
    time.sleep(0.5)
    print("║     resgatar sua querida filha.                          ║")
    time.sleep(0.5)
    print("║                                                          ║")
    time.sleep(0.5)
    print("║                                                          ║")
    print("║                Zombies of Coffee ☕©                     ║")
    time.sleep(0.5)
    print("╚══════════════════════════════════════════════════════════╝")
                 
def caminho():
    time.sleep(0.8)
    print("╔══════════════════════════════════════════════════════════╗")
    print("║     Vicent sai da sua vila em busca do castelo do        ║")
    print("║     Feiticeiro Negro.                                    ║")
    print("║     ⩥ Qual caminho ele deverá optar?                     ║")
    time.sleep(1)
    print("║                                                          ║")
    print("║     A) Entrar na floresta e seguir um atalho?            ║")
    time.sleep(1)
    print("║     B) Atravessar a ponte e seguir pelas vilas?          ║")
    print("║                                                          ║")
    print("║                                                          ║")
    print("╚══════════════════════════════════════════════════════════╝")


    
def castelo():
    print("╔══════════════════════════════════════════════════════════╗")
    print("║     Ao final da sua jornada, Vincent encontra o castelo  ║")
    print("║     do maligno feiticeiro.                               ║")
    print("║     ⩥ Qual plano ele escolhe para resgatar Aurora?       ║")
    time.sleep(1)
    print("║                                                          ║")
    print("║     A) Lutar contra o Feiticeiro Negro e mata-lo?        ║")
    time.sleep(1)
    print("║     B) Entrar escondido no castelo e fugir com Aurora?   ║")
    print("║                                                          ║")
    print("║                                                          ║")
    print("╚══════════════════════════════════════════════════════════╝")

def finalA():
    print("╔══════════════════════════════════════════════════════════╗")
    print("║     Vincent derrota o Feiticeiro Negro e ele retorna em  ║")
    print("║     segurança a vila com sua filha.                      ║")
    print("║                                                          ║")
    print("║     Fim.                                                 ║")
    time.sleep(0.8)
    print("║     ?...                                                 ║")
    print("║                                                          ║")
    print("║                                                          ║")
    print("║                                                          ║")
    print("║                      ☕ ZoC ☕                           ║")
    print("╚══════════════════════════════════════════════════════════╝")
                 
def finalB():
    print("╔══════════════════════════════════════════════════════════╗")
    print("║     Apos Vincent encontrar Aurora em uma sala trancada   ║")
    print("║     ele consegue abrir a fechadura e libertar sua filha, ║")
    print("║     os dois deixam o castelo do feiticeiro e voltam      ║")
    print("║     para a vila.                                         ║")
    print("║     Os itens coletado por Vincent ao longo da sua        ║")
    print("║     jornada o ajudarão a protejer sua vila de futuros    ║")
    print("║     ataques do Feitifeiro Negro.                         ║")
    print("║                                                          ║")
    print("║     Fim.                                                 ║")
    time.sleep(0.8)
    print("║     ?...                                                 ║")
    print("║                                                          ║")
    print("║                                                          ║")
    print("║                    ☕ ZoC ☕                             ║")
    print("╚══════════════════════════════════════════════════════════╝")
                 


    
