import time

def historia():

    
    print("╔══════════════════════════════════════════════════════════╗")
    time.sleep(0.5)
    print("║              ᖙ Em Busca da Aurora ᖚ                      ║")
    time.sleep(0.5)
    print("║                                                          ║")
    time.sleep(0.5)
    print("║     Em uma região pacata e calma no norte, Vincent,      ║")
    time.sleep(0.5)
    print("║     um camponês vive feliz com sua esposa e sua filha    ║")
    time.sleep(0.5)
    print("║     Aurora na sua vila junto com outras famílias, até    ║")
    time.sleep(0.5)   
    print("║     que um certo dia Aurora foi sequestrada pelo         ║")
    time.sleep(0.5)
    print("║     Feiticeiro Negro e aprisionada em um castelo ao      ║")
    time.sleep(0.5)
    print("║     longe da sua vila.                                   ║")
    time.sleep(0.5)
    print("║     Desolado pelo sequestro da sua filha, Vincent sai    ║")
    time.sleep(0.5)
    print("║     pela estrada em busca do caminho para o castelo      ║")
    time.sleep(0.5)
    print("║     do feiticeiro, neste caminho ele terá que solucionar ║")
    time.sleep(0.5)
    print("║     quebra-cabeças pela sua jornada e coletar itens      ║")
    time.sleep(0.5)
    print("║     para conseguir derrotar seu inimigo.                 ║")
    time.sleep(0.5)
    print("║     ⩥ Cabe a você ajuda-lo em sua jornada para           ║")
    time.sleep(0.5)
    print("║     resgatar sua querida filha.                          ║")
    time.sleep(0.2)
    print("║                                                          ║")
    time.sleep(0.2)
    print("║                                                          ║")
    time.sleep(0.2)
    print("╚══════════════════════════════════════════════════════════╝")


def caminho():
    time.sleep(0.8)
    print("╔══════════════════════════════════════════════════════════╗")
    print("║     Vicent sai da sua vila em busca do castelo do        ║")
    print("║     Feiticeiro Negro.                                    ║")
    print("║     ⩥ Qual caminho ele deverá optar?                     ║")
    time.sleep(3)
    print("║                                                          ║")
    print("║     A) Entrar na floresta e seguir um atalho?            ║")
    time.sleep(2)
    print("║     B) Atravessar a ponte e seguir pelas vilas?          ║")
    print("║                                                          ║")
    print("║                                                          ║")
    print("╚══════════════════════════════════════════════════════════╝")